CREATE TABLE IF NOT EXISTS "applications" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"date" text,
	"company" text,
	"role" text,
	"score" text,
	"score_num" real,
	"status" text,
	"has_pdf" boolean,
	"report_id" text,
	"drive_report_url" text,
	"drive_cv_url" text,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"report_content" text,
	"user_email" text
);
